// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
import '@angular/forms';
// Telerik
import '@progress/kendo-angular-dialog';
import '@progress/kendo-angular-inputs';
import '@progress/kendo-angular-grid';
import '@progress/kendo-angular-intl';
import '@progress/kendo-data-query';
import '@progress/kendo-angular-l10n'
import '@progress/kendo-angular-dropdowns';
import '@progress/kendo-angular-buttons';
import '@progress/kendo-angular-dateinputs';
// RxJS
import 'rxjs';
// Lodash
import 'lodash';
// Others
import 'fullcalendar';
import 'angular-tree-component';
import 'bootstrap';
import 'jquery';
import 'jquery.browser';
import 'moment';
import 'ng2-bootstrap';
import 'ng2-tag-input';
import 'ng2-toastr';

// CSS
import 'fullcalendar/dist/fullcalendar.css';
import 'toastr/build/toastr.css';
import '../styles/kendo-all.css';
import '../styles/styles.bundle.css';
import '../styles/styles.css';
